name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/github-ec2
          chmod 600 ~/.ssh/github-ec2

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github-ec2 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'bash ~/deploy/deploy.sh'
