# name: Build and Deploy to S3

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [20.x]

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}

#       - name: Install dependencies
#         run: npm install
#         working-directory: ./Frontend

#       - name: Build project
#         run: npm run build
#         working-directory: ./Frontend

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-2

#       - name: Clear existing files from S3 (optional but safe alternative to --delete)
#         run: aws s3 rm s3://${{ secrets.AWS_S3_BUCKET }} --recursive

#       - name: Upload to S3
#         run: |
#           aws s3 sync ./Frontend/dist s3://${{ secrets.AWS_S3_BUCKET }} \
#             --acl public-read \
#             --follow-symlinks

#       - name: Invalidate CloudFront
#         uses: chetan/invalidate-cloudfront-action@master
#         with:
#           distribution: ${{ secrets.AWS_DISTRIBUTION_PRODUCTION }}
#           paths: '/*'
#         env:
#           AWS_REGION: us-east-2
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
name: letphil ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v1
      - run: cd Frontend && npm install && npm run build
      # - run: npm run build
      - uses: aws-actions/aws-cli@v2
        with:
         command: s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-2"
          SOURCE_DIR: "Frontend/dist"

      - uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_PRODUCTION }}
          PATHS: "/*"
          AWS_REGION: "us-east-2"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

# aws-actions/aws-cli@v2
# name: Deploy to S3

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}
#       - name: Upload to S3
#         uses: aws-actions/aws-cli@v2
#         with:
#           # You can specify the command here
#           # In this example, it's copying all the files in the current directory to the S3 bucket
#           # and deleting any files that no longer exist in the repository
#           command: s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} --delete
